elasticsearch:
  image: elasticsearch:2.4.0
  command: elasticsearch -Des.network.host=0.0.0.0 -Dhttp.cors.enabled=yes -Dhttp.cors.allow-origin=/.*/
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5140:5140"
    - "5141:5141"
    - "5142:5142"
  links:
    - elasticsearch

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch

kopf:
  image: labynocle/docker_kopf
  ports:
    - "80:80"
